#!/usr/bin/env python3
"""
xrick port -- sound engine extractor (T19 / audio-sndh.md P1).

Lifts the same 0x44C10-0x5324F byte window `re/build_sndh.py` packages into
rick_dangerous.sndh, but emits it as a plain C byte array with NO relocating stub and
NO SNDH header. Unlike a generic SNDH player, the port controls its own AtariMachine
instance and uploads the blob directly at build_sndh.py's OWN rel()-adjusted address --
so none of build_sndh.py's hand-assembled relocation/init trampolines are needed here.
This script only does the "lift the blob" half of build_sndh.py.

IMPORTANT, found the hard way (P8 smoke test, 2026-09-10): the blob's *content* is
position-DEPENDENT -- every internal absolute reference (table lookups, jsr targets,
the timer-A ISR vector setup_timer_a installs) is a literal encoded in the bytes
themselves, and when the source dump is atari_ram_1M.bin (preferred here for complete
PCM data, same as build_sndh.py), those literals were fixed up by GEMDOS relocation to
that dump's OWN load address -- NOT atari_ram.bin's canonical 0x44C10 numbering.
Directly verified: atari_ram.bin's setup_timer_a installs ISR address 0x45022 at vector
0x134; atari_ram_1M.bin's installs 0x0042FCE at the same site -- off by exactly DELTA
(-0x2054). So every address this script exports (upload target AND all entry points)
MUST be the same rel()-adjusted address build_sndh.py uses, not the canonical one --
uploading rel()-adjusted content at the canonical address (this script's first,
buggy version) silently breaks every internal reference by DELTA.

Delta-finding logic (the ANCHOR scan, the self-check against music_track_table) is
copied from build_sndh.py rather than imported, so this tool has no dependency on
re/'s layout beyond the two dump files it reads. MEMORY.md S6: the load delta is not
fixed and must be measured every time, never hardcoded.

Output: src/dat_sndh_engine.c -- a const U8[] blob plus the ST-address constants
syssnd.c needs (engine base/end, and the four entry points play_music/music_tick/
setup_timer_a/silence_all_channels/reset_sound_chip cited in audio-sndh.md).
"""

import os, struct, sys

HERE = os.path.dirname(os.path.abspath(__file__))          # xrick/xrick/tools
PORT_SRC = os.path.normpath(os.path.join(HERE, "..", "src"))  # xrick/xrick/src
RE_DIR = os.path.normpath(os.path.join(HERE, "..", "..", "..", "re"))  # repo/re

CANDIDATES = ["atari_ram_1M.bin", "atari_ram.bin"]
for name in CANDIDATES:
    path = os.path.join(RE_DIR, name)
    if os.path.exists(path):
        DUMP = name
        D = open(path, "rb").read()
        break
else:
    sys.exit(f"no memory dump found in {RE_DIR}")

# Reference addresses, in atari_ram.bin numbering (identical to build_sndh.py)
REF_RESET   = 0x44C10         # reset_sound_chip
REF_PLAY    = 0x44CCE         # play_music(d0 = track, d1 = variant)
REF_TICK    = 0x44E0C         # music_tick (once per 50 Hz frame)
REF_TIMERA  = 0x45006         # setup_timer_a  -- required for PCM
REF_SILENCE = 0x45528         # silence_all_channels -- clears stale channel state
REF_TRACKS  = 0x44F08         # music_track_table
REF_IMG_END = 0x53250         # end of the program image
N_TRACKS    = 29

ANCHOR = bytes.fromhex("13fc0007ffff88000039003fffff8802")

def find_delta():
    hits, i = [], 0
    while True:
        i = D.find(ANCHOR, i)
        if i < 0:
            break
        hits.append(i); i += 1
    if not hits:
        sys.exit(f"{DUMP}: could not locate reset_sound_chip -- is this a Rick Dangerous dump?")
    delta = hits[0] - REF_RESET
    tt = REF_TRACKS + delta
    for k in range(N_TRACKS):
        ty = struct.unpack_from(">h", D, tt + k * 8)[0]
        if ty not in (0, 1, 2):
            sys.exit(f"{DUMP}: delta {delta:#x} rejected -- track {k} has type {ty}")
    return delta

DELTA = find_delta()
rel   = lambda a: a + DELTA

IMG_BASE  = rel(REF_RESET)
IMG_END   = rel(REF_IMG_END)
DUMP_END  = len(D)

full = IMG_END - IMG_BASE
have = D[IMG_BASE:min(DUMP_END, IMG_END)]
blob = have + bytes(full - len(have))
missing = full - len(have)
if missing:
    print(f"WARNING: {DUMP} is short by {missing} bytes past the engine window -- "
          f"zero-filled; some subtune(s) may be silent", file=sys.stderr)

# ---------------------------------------------------------------- emit C source
OUT_H = os.path.join(PORT_SRC, "..", "include", "dat_sndh_engine.h")
OUT_H = os.path.normpath(OUT_H)
OUT_C = os.path.join(PORT_SRC, "dat_sndh_engine.c")

def c_bytes(b):
    lines = []
    for i in range(0, len(b), 20):
        lines.append(",".join(str(x) for x in b[i:i+20]))
    return ",\n  ".join(lines)

HEADER_COMMENT = f"""/*
 * GENERATED by tools/extract_sound_engine.py -- do not hand-edit.
 *
 * The Rick Dangerous (Atari ST) sound engine -- code and tables -- lifted verbatim
 * from a Hatari RAM snapshot of the running original game (re/{DUMP}). This is the
 * exact 68000 replay code and PSG/sample data from the shipped game, not a
 * re-synthesis. See audio-sndh.md for the design this feeds, and
 * re/assets-manifest.md / re/algo-music.md for the reverse-engineering behind it.
 *
 * Source window: 0x{REF_RESET:05X}-0x{REF_IMG_END-1:05X} in atari_ram.bin numbering
 * ({full} bytes). Captured from: re/{DUMP}, load delta {DELTA:+#x} at extraction time --
 * MEMORY.md S6: not a fixed constant, re-run this script if the dump changes.
 *
 * The addresses below are this dump's OWN numbering (canonical + delta), matching
 * where the blob's internal absolute references actually point -- see the P8 note
 * above. syssnd.c uploads the blob at SNDH_ENGINE_BASE and calls the SNDH_FN_* entry
 * points directly; no relocating stub is needed (unlike re/build_sndh.py's SNDH,
 * which needs one only because a generic SNDH player picks its own load address --
 * here we choose it ourselves, so we choose the address that already matches).
 */"""

with open(OUT_H, "w", newline="\n") as f:
    f.write(f"""{HEADER_COMMENT}

#ifndef _DAT_SNDH_ENGINE_H
#define _DAT_SNDH_ENGINE_H

#include "system.h"	/* defines ENABLE_SOUND (via config.h) */

#ifdef ENABLE_SOUND

/* ---- this dump's own address numbering (canonical + {DELTA:+#x}) -- see the P8 note
   above. Upload() the blob at SNDH_ENGINE_BASE and every SNDH_FN_ and
   SNDH_TRACK_TABLE address is then correct as-is; do NOT "simplify" these back to
   the canonical 0x44C10-numbering constants without also switching the source dump
   to one with delta 0, or every internal absolute reference breaks by the delta. */
#define SNDH_ENGINE_BASE   0x{IMG_BASE:05X}u   /* reset_sound_chip; Upload() target */
#define SNDH_ENGINE_END    0x{IMG_END:05X}u    /* exclusive */
#define SNDH_FN_RESET      0x{rel(REF_RESET):05X}u          /* reset_sound_chip() */
#define SNDH_FN_PLAY       0x{rel(REF_PLAY):05X}u            /* play_music(d0=track, d1=variant) */
#define SNDH_FN_TICK       0x{rel(REF_TICK):05X}u            /* music_tick(), call at 50 Hz */
#define SNDH_FN_TIMERA     0x{rel(REF_TIMERA):05X}u          /* setup_timer_a() -- required for PCM */
#define SNDH_FN_SILENCE    0x{rel(REF_SILENCE):05X}u         /* silence_all_channels() */
#define SNDH_TRACK_TABLE   0x{rel(REF_TRACKS):05X}u          /* music_track_table[29], 8 bytes/entry */
#define SNDH_N_TRACKS      {N_TRACKS}

extern const unsigned int sndh_engine_blob_len;
extern const unsigned char sndh_engine_blob[{full}];

#endif /* ENABLE_SOUND */

#endif /* _DAT_SNDH_ENGINE_H */

/* eof */
""")

with open(OUT_C, "w", newline="\n") as f:
    f.write(f"""{HEADER_COMMENT}

#include "dat_sndh_engine.h"

#ifdef ENABLE_SOUND

const unsigned int sndh_engine_blob_len = {full}u;
const unsigned char sndh_engine_blob[{full}] = {{
  {c_bytes(blob)}
}};

#endif /* ENABLE_SOUND */

/* eof */
""")

print(f"dump         {DUMP}  ({len(D)} bytes)")
print(f"relocation   {DELTA:+#x} vs atari_ram.bin numbering")
print(f"blob         0x{REF_RESET:05X}-0x{REF_IMG_END-1:05X} ({full} bytes){'  (' + str(missing) + ' zero-filled)' if missing else ''}")
print(f"wrote        {OUT_H}")
print(f"wrote        {OUT_C}")
