"""
Shared helpers for the kb2/gen_rd2_*.py generators (PLAN.md T41 step 2 / port-rd2.md P1).

Every gen_rd2_*.py script produces one or more xrick/xrick/src/rd2/dat_rd2_*.c +
include/rd2/dat_rd2_*.h pairs. Convention mirrors xrick/xrick/src/rd1/dat_sndh_engine.c
(RD1's own generated-blob precedent): a "GENERATED -- do not hand-edit" header comment
naming the script and the exact source file(s)/address(es) read, then plain C arrays.
No transformation of game data beyond byte-for-byte extraction -- ports-rd2.md P1's
rule: re-derive from the source bytes, never hand-transcribe.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC_RD2 = os.path.join(ROOT, "xrick", "xrick", "src", "rd2")
INC_RD2 = os.path.join(ROOT, "xrick", "xrick", "include", "rd2")
ASSETS = os.path.join(HERE, "assets")
MAPDIR = os.path.join(ASSETS, "maps")
LEVELS = os.path.join(ASSETS, "levels")


def c_bytes(data, per_line=20):
    """Format a bytes-like object as a C initializer list body (no braces), RD1 dat_sndh_engine.c style."""
    lines = []
    for i in range(0, len(data), per_line):
        lines.append(",".join(str(b) for b in data[i:i + per_line]))
    return ",\n  ".join(lines)


def c_words(words, per_line=12, signed=False):
    """Format a list of 16-bit ints as a C initializer list body."""
    lines = []
    for i in range(0, len(words), per_line):
        lines.append(",".join(str(w) for w in words[i:i + per_line]))
    return ",\n  ".join(lines)


def write_pair(basename, header_comment, header_body, source_body, includes=("system.h",)):
    """Write include/rd2/<basename>.h and src/rd2/<basename>.c."""
    guard = "_" + basename.upper() + "_H"
    hpath = os.path.join(INC_RD2, basename + ".h")
    with open(hpath, "w", newline="\n") as f:
        f.write(header_comment)
        f.write("\n#ifndef %s\n#define %s\n\n" % (guard, guard))
        for inc in includes:
            f.write('#include "%s"\n' % inc)
        f.write("\n")
        f.write(header_body)
        f.write("\n#endif /* %s */\n\n/* eof */\n" % guard)
    cpath = os.path.join(SRC_RD2, basename + ".c")
    with open(cpath, "w", newline="\n") as f:
        f.write(header_comment)
        f.write('\n#include "%s.h"\n\n' % basename)
        f.write(source_body)
        f.write("\n/* eof */\n")
    print("wrote %s, %s" % (hpath, cpath))


def gen_header(script, sources, notes=""):
    lines = [
        "/*",
        " * GENERATED by kb2/%s -- do not hand-edit." % script,
        " *",
    ]
    for s in sources.split("\n"):
        lines.append(" * " + s if s else " *")
    if notes:
        lines.append(" *")
        for n in notes.split("\n"):
            lines.append(" * " + n if n else " *")
    lines.append(" */")
    return "\n".join(lines) + "\n"
